<a href="https://colab.research.google.com/github/rajkr5446/learning-ml/blob/numpy/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basics of Numpy

In [ ]:
import numpy as np

In [ ]:
np_array = np.array([i for i in range(10)])
print(np_array)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
type(np_array)

numpy.ndarray

#Creating a multi-dimensional array

In [ ]:
#creating a 1-d array
a = np.array([1, 2, 3, 4, 5])
print(a)
a.shape

[1 2 3 4 5]


(5,)

*   np_array.shape ->> (number of rows, number of columns)
*   for 1-D array it just gives (number of columns, )

In [ ]:
b = np.array([[1], [2], [3]])
print(b)
b.shape

[[1]
 [2]
 [3]]


(3, 1)

In [ ]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(c)
c.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

# Numpy arrays with floating points

In [ ]:
d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]], dtype=float)
print(d)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


# Initializing array with values




In [ ]:
#initial value 0   3 rows and 4 columns
x = np.zeros((3, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#initial value 1   3 rows and 4 columns
y = np.ones((3, 4))
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


we can note that functions zeros and ones by default create floating data types

In [ ]:
#initial value 5  3 rows and 4 columns
z = np.full((3, 4), 5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


using below code we can change the default float data type of zeros and ones

In [ ]:
#initial value 1   3 rows and 4 columns
y = np.ones((3, 4), dtype=int)
print(y)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


# Creating identity matrix

In [ ]:
#here we pass only one value of shape as identity matrix is a square matrix
id_mat = np.eye(4)
print(id_mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#can we change the default float data type?
id_mat = np.eye(4, dtype=int)
print(id_mat)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


# Creating array with random values

In [ ]:
#this will create a 3x4 array with random float values b/w 0 and 1
np_rand = np.random.random((3, 4))
print(np_rand)

[[0.62419863 0.28557704 0.69445548 0.88454401]
 [0.61247233 0.70612637 0.01158543 0.7093167 ]
 [0.64090894 0.5100294  0.02204294 0.46187924]]


In [ ]:
#to create a random integer values array within a specific range we have to use randint
#below 10 is stating value, 100 is last value and shape is 3x4
np_randInt = np.random.randint(10, 100, (3, 4))
print(np_randInt)

[[78 79 31 20]
 [67 61 72 80]
 [43 15 90 72]]


# Evenly spaced array

In [ ]:
#evenly spaced array --> with size of array
np_even = np.linspace(10, 30, 5)
print(np_even)

[10. 15. 20. 25. 30.]


In [ ]:
#evenly spaced array --> with size of step
np_even_step = np.arange(10, 30, 5)
print(np_even_step)

[10 15 20 25]


we can note the difference that in **linspace** last value is **included** but in **arange** last value is **not included**

#Converting list to numpy array

In [ ]:
p_list = [1, 2, 3, 4 ,5]
print(p_list)
np_list_array = np.asarray(p_list)
print(np_list_array)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [ ]:
#using this we can also convert tuple to numpy array
p_tuple = (1, 2, 3, 4, 5)
print(p_tuple)
np_tuple_array = np.asarray(p_tuple)
print(np_tuple_array)

(1, 2, 3, 4, 5)
[1 2 3 4 5]


#Analysis of numpy array

In [ ]:
#initialize a numpy array of random integers b/w 10 and 90 of size 5x5
np_array_int = np.random.randint(10, 90, (5, 5))
print(np_array_int)

[[56 77 22 76 57]
 [68 60 31 23 18]
 [75 65 71 89 17]
 [89 65 12 26 26]
 [40 66 65 38 54]]




1.   Shape of array



In [ ]:
np_array_int.shape

(5, 5)



2. Number of dimensions



In [ ]:
np_array_int.ndim

2

3. number of elements (size)

In [ ]:
np_array_int.size

25

4. Datatype of elements

In [ ]:
np_array_int.dtype

dtype('int64')

#Mathematical operations on numpy arrays

In [ ]:
#when we try to add two lists it just joins them
list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
print(list_1 + list_2)

[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
#but in numpy arrays we can do mathematical operations
numpy_a = np.random.randint(0, 10, (3, 3))
numpy_b = np.random.randint(10, 20, (3, 3))
print(numpy_a)
print(numpy_b)

[[6 3 4]
 [3 3 6]
 [0 3 1]]
[[10 16 15]
 [15 14 13]
 [15 16 11]]


1. Addition

In [ ]:
print(numpy_a +numpy_b)
print(np.add(numpy_a, numpy_b))

[[16 19 19]
 [18 17 19]
 [15 19 12]]
[[16 19 19]
 [18 17 19]
 [15 19 12]]


2. Subtraction

In [ ]:
print(numpy_a - numpy_b)
print(np.subtract(numpy_a, numpy_b))

[[ -4 -13 -11]
 [-12 -11  -7]
 [-15 -13 -10]]
[[ -4 -13 -11]
 [-12 -11  -7]
 [-15 -13 -10]]


3. Multiplication

In [ ]:
print(numpy_a * numpy_b)
print(np.multiply(numpy_a, numpy_b))

[[60 48 60]
 [45 42 78]
 [ 0 48 11]]
[[60 48 60]
 [45 42 78]
 [ 0 48 11]]


4. Division

In [ ]:
print(numpy_a / numpy_b)
print(np.divide(numpy_a, numpy_b))

[[0.6        0.1875     0.26666667]
 [0.2        0.21428571 0.46153846]
 [0.         0.1875     0.09090909]]
[[0.6        0.1875     0.26666667]
 [0.2        0.21428571 0.46153846]
 [0.         0.1875     0.09090909]]


#Numpy array manipulations

1. Transpose

In [ ]:
np_array_rand = np.random.randint(0, 10, (2, 3))
print(np_array_rand)
print(np_array_rand.shape)

[[4 8 5]
 [4 1 2]]
(2, 3)


In [ ]:
#Transpose --> using np.transpose
trans1 = np.transpose(np_array_rand)
print(trans1)
print(trans1.shape)

[[4 4]
 [8 1]
 [5 2]]
(3, 2)


In [ ]:
#Transpose --> using np_array.T
trans2 = np_array_rand.T
print(trans2)
print(trans2.shape)

[[4 4]
 [8 1]
 [5 2]]
(3, 2)


2. Reshaping an array

In [ ]:
#reshaping using np_array.reshape
np_array_rand_reshaped = np_array_rand.reshape(3, 2)
print(np_array_rand_reshaped)
print(np_array_rand_reshaped.shape)

[[4 8]
 [5 4]
 [1 2]]
(3, 2)
